/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version Versions.kotlin
    kotlin("kapt") version Versions.kapt

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(platform(Platform.kotlin))

    testImplementation(Test.kotlin)
    testImplementation(Test.jUnit)

    kapt(Kapt.dagger)

    implementation(StandardLibrary.jdk8)
    implementation(StandardLibrary.guava)
    implementation(Impl.dagger)
}

version = Publish.version
group = Publish.group

publishing {
    publications {
        create<MavenPublication>(Publish.name) {
            from(components["java"])
        }
    }
}